---
# tasks file for cloudlinux-exporter-role

# Check if this is a Cloudlinux server with LVE installed

- name: Check if Cloudlinux Server
  stat:
    path: /usr/sbin/cloudlinux-statistics
  register: cloudlinux_installed

- name: Include install tasks if the Cloudlinux is installed
  include_tasks: install.yml
  when: cloudlinux_installed.stat.exists